# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrmArma <- function(x, mean, sigma, logd = TRUE) {
    .Call('_dmatch_dmvnrmArma', PACKAGE = 'dmatch', x, mean, sigma, logd)
}

likelihood_para_cpp <- function(X, Y, mu_x, mu_y, A, d, D1, D2, logd = TRUE) {
    .Call('_dmatch_likelihood_para_cpp', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, A, d, D1, D2, logd)
}

dmvtArma <- function(X, mu, sigma, df, log) {
    .Call('_dmatch_dmvtArma', PACKAGE = 'dmatch', X, mu, sigma, df, log)
}

callmtCov <- function(X, nu) {
    .Call('_dmatch_callmtCov', PACKAGE = 'dmatch', X, nu)
}

likelihood_para_t_cpp <- function(X, Y, mu_x, mu_y, A, d, Sigma1, Sigma2, df, logd = TRUE) {
    .Call('_dmatch_likelihood_para_t_cpp', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, A, d, Sigma1, Sigma2, df, logd)
}

rotation_matrix <- function(theta) {
    .Call('_dmatch_rotation_matrix', PACKAGE = 'dmatch', theta)
}

rotation_matrix_dev <- function(theta) {
    .Call('_dmatch_rotation_matrix_dev', PACKAGE = 'dmatch', theta)
}

run_simple_est_cpp <- function(X, Y, x1, y1, steps = 1000L) {
    .Call('_dmatch_run_simple_est_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, steps)
}

run_simple_est_theta_cpp <- function(X, Y, x1, y1, steps = 500L) {
    .Call('_dmatch_run_simple_est_theta_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, steps)
}

run_simple_est_theta_one_cluster_cpp <- function(X, x1, steps = 500L) {
    .Call('_dmatch_run_simple_est_theta_one_cluster_cpp', PACKAGE = 'dmatch', X, x1, steps)
}

run_simple_est_theta_coord_cpp <- function(X, Y, x1, y1, steps = 500L) {
    .Call('_dmatch_run_simple_est_theta_coord_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, steps)
}

run_simple_est_theta_three_cluster_cpp <- function(X, Y, Z, x1, y1, z1, steps = 500L) {
    .Call('_dmatch_run_simple_est_theta_three_cluster_cpp', PACKAGE = 'dmatch', X, Y, Z, x1, y1, z1, steps)
}

run_simple_est_coord_cpp <- function(X, Y, x1, y1, steps = 1000L) {
    .Call('_dmatch_run_simple_est_coord_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, steps)
}

run_simple_est_coord_three_clusters_cpp <- function(X, Y, Z, x1, y1, z1, steps = 1000L) {
    .Call('_dmatch_run_simple_est_coord_three_clusters_cpp', PACKAGE = 'dmatch', X, Y, Z, x1, y1, z1, steps)
}

run_simple_t_distribution_est_cpp <- function(X, Y, x1, y1, steps = 1000L, nu = 5) {
    .Call('_dmatch_run_simple_t_distribution_est_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, steps, nu)
}

run_simple_t_distribution_est_theta_cpp <- function(X, Y, x1, y1, steps = 1000L, nu = 5) {
    .Call('_dmatch_run_simple_t_distribution_est_theta_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, steps, nu)
}

run_simple_angle_t_distribution_est_cpp <- function(X, Y, x1, y1, angle_list, steps = 1000L, nu = 5) {
    .Call('_dmatch_run_simple_angle_t_distribution_est_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, angle_list, steps, nu)
}

run_simple_angle_t_distribution_likelihood_est_cpp <- function(X, Y, x1, y1, angle_list, steps = 1000L, nu = 5) {
    .Call('_dmatch_run_simple_angle_t_distribution_likelihood_est_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, angle_list, steps, nu)
}

gradient_A <- function(XX, YY, X_t, Y_t, mu_x, mu_y, estA, estd, n, m, p, D1_inv, D2_inv) {
    .Call('_dmatch_gradient_A', PACKAGE = 'dmatch', XX, YY, X_t, Y_t, mu_x, mu_y, estA, estd, n, m, p, D1_inv, D2_inv)
}

gradient_d <- function(X, Y, mu_x, mu_y, estA, estd, n, m, p, D1_inv, D2_inv, D12_inv_sum) {
    .Call('_dmatch_gradient_d', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estA, estd, n, m, p, D1_inv, D2_inv, D12_inv_sum)
}

select_stepsize_for_A <- function(X, Y, mu_x, mu_y, estA, estd, ll, A_gradient, p, D1, D2, gamma, down) {
    .Call('_dmatch_select_stepsize_for_A', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estA, estd, ll, A_gradient, p, D1, D2, gamma, down)
}

select_stepsize_for_d <- function(X, Y, mu_x, mu_y, estA, estd, ll, d_gradient, p, D1, D2, gamma, down) {
    .Call('_dmatch_select_stepsize_for_d', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estA, estd, ll, d_gradient, p, D1, D2, gamma, down)
}

select_stepsize_for_A_alt <- function(X, Y, mu_x, mu_y, estA, estd, ll, A_gradient, p, D1, D2, beta) {
    .Call('_dmatch_select_stepsize_for_A_alt', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estA, estd, ll, A_gradient, p, D1, D2, beta)
}

select_stepsize_for_d_alt <- function(X, Y, mu_x, mu_y, estA, estd, ll, d_gradient, p, D1, D2, beta) {
    .Call('_dmatch_select_stepsize_for_d_alt', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estA, estd, ll, d_gradient, p, D1, D2, beta)
}

run_est_with_gradient_descent_cpp <- function(X, Y, x1, y1, steps, gamma, down) {
    .Call('_dmatch_run_est_with_gradient_descent_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, steps, gamma, down)
}

gradient_theta <- function(X, Y, mu_x, mu_y, estTheta, estA, estd, n, m, p, D1_inv, D2_inv) {
    .Call('_dmatch_gradient_theta', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estTheta, estA, estd, n, m, p, D1_inv, D2_inv)
}

select_stepsize_for_theta <- function(X, Y, mu_x, mu_y, estTheta, estA, estd, ll, Theta_gradient, p, D1, D2, gamma, down) {
    .Call('_dmatch_select_stepsize_for_theta', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estTheta, estA, estd, ll, Theta_gradient, p, D1, D2, gamma, down)
}

run_est_with_gradient_descent_angle_search_cpp <- function(X, Y, x1, y1, steps, gamma, down) {
    .Call('_dmatch_run_est_with_gradient_descent_angle_search_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, steps, gamma, down)
}

gradient_A_t_dis <- function(X, Y, Sigma1_inv, Sigma2_inv, mu_x, mu_y, estA, estd, n, m, p) {
    .Call('_dmatch_gradient_A_t_dis', PACKAGE = 'dmatch', X, Y, Sigma1_inv, Sigma2_inv, mu_x, mu_y, estA, estd, n, m, p)
}

gradient_d_t_dis <- function(X, Y, Sigma1_inv, Sigma2_inv, mu_x, mu_y, estA, estd, n, m, p) {
    .Call('_dmatch_gradient_d_t_dis', PACKAGE = 'dmatch', X, Y, Sigma1_inv, Sigma2_inv, mu_x, mu_y, estA, estd, n, m, p)
}

select_stepsize_for_A_t_dis <- function(X, Y, mu_x, mu_y, estA, estd, ll, A_gradient, p, Sigma1, Sigma2, nu, gamma, down) {
    .Call('_dmatch_select_stepsize_for_A_t_dis', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estA, estd, ll, A_gradient, p, Sigma1, Sigma2, nu, gamma, down)
}

select_stepsize_for_d_t_dis <- function(X, Y, mu_x, mu_y, estA, estd, ll, d_gradient, p, Sigma1, Sigma2, nu, gamma, down) {
    .Call('_dmatch_select_stepsize_for_d_t_dis', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estA, estd, ll, d_gradient, p, Sigma1, Sigma2, nu, gamma, down)
}

run_est_with_gradient_descent_t_dis_cpp <- function(X, Y, x1, y1, gamma, down, steps = 1000L, nu = 5) {
    .Call('_dmatch_run_est_with_gradient_descent_t_dis_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, gamma, down, steps, nu)
}

gradient_theta_t_dis <- function(X, Y, Sigma1_inv, Sigma2_inv, mu_x, mu_y, estTheta, estA, estd, n, m, p) {
    .Call('_dmatch_gradient_theta_t_dis', PACKAGE = 'dmatch', X, Y, Sigma1_inv, Sigma2_inv, mu_x, mu_y, estTheta, estA, estd, n, m, p)
}

select_stepsize_for_theta_t_dis <- function(X, Y, mu_x, mu_y, estTheta, estA, estd, ll, Theta_gradient, p, Sigma1, Sigma2, nu, gamma, down) {
    .Call('_dmatch_select_stepsize_for_theta_t_dis', PACKAGE = 'dmatch', X, Y, mu_x, mu_y, estTheta, estA, estd, ll, Theta_gradient, p, Sigma1, Sigma2, nu, gamma, down)
}

run_est_with_gradient_descent_angle_search_t_dis_cpp <- function(X, Y, x1, y1, gamma, down, steps = 1000L, nu = 5) {
    .Call('_dmatch_run_est_with_gradient_descent_angle_search_t_dis_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, gamma, down, steps, nu)
}

run_simple_angle_est_cpp <- function(X, Y, x1, y1, angle_list, steps = 1000L) {
    .Call('_dmatch_run_simple_angle_est_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, angle_list, steps)
}

run_simple_angle_likelihood_est_cpp <- function(X, Y, x1, y1, angle_list, steps = 1000L) {
    .Call('_dmatch_run_simple_angle_likelihood_est_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, angle_list, steps)
}

run_simple_est_theta_coordinate_descent_cpp <- function(X, Y, x1, y1, steps = 20L, gra_steps = 10L) {
    .Call('_dmatch_run_simple_est_theta_coordinate_descent_cpp', PACKAGE = 'dmatch', X, Y, x1, y1, steps, gra_steps)
}

run_simple_est_theta_coordinate_descent_one_cluster_cpp <- function(X, x1, steps = 20L, gra_steps = 20L) {
    .Call('_dmatch_run_simple_est_theta_coordinate_descent_one_cluster_cpp', PACKAGE = 'dmatch', X, x1, steps, gra_steps)
}

run_simple_est_theta_coordinate_descent_three_cluster_cpp <- function(X, Y, Z, x1, y1, z1, steps = 20L, gra_steps = 10L) {
    .Call('_dmatch_run_simple_est_theta_coordinate_descent_three_cluster_cpp', PACKAGE = 'dmatch', X, Y, Z, x1, y1, z1, steps, gra_steps)
}

